---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: sc-account-301c275c-0001-43dc-b259-8fa0ba6be4c8
      containers:
        - name: workload
          image: petclinicacrkvnai2avleko2.azurecr.io/petclinic:0.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sc-pg-secret
                  key: spring.cloud.azure.credential.client-id
            - name: AZURE_MANAGED_IDENTITY_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-pg-secret
                  key: spring.cloud.azure.credential.client-id
            - name: SPRING_CLOUD_AZURE_CREDENTIAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sc-pg-secret
                  key: spring.cloud.azure.credential.client-id
            - name: SPRING_CLOUD_AZURE_CREDENTIAL_MANAGED_IDENTITY_ENABLED
              valueFrom:
                secretKeyRef:
                  name: sc-pg-secret
                  key: spring.cloud.azure.credential.managed-identity-enabled
            - name: SPRING_DATASOURCE_AZURE_PASSWORDLESS_ENABLED
              valueFrom:
                secretKeyRef:
                  name: sc-pg-secret
                  key: spring.datasource.azure.passwordless-enabled
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: sc-pg-secret
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sc-pg-secret
                  key: spring.datasource.username
          envFrom:
            - secretRef:
                name: sc-pg-secret
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: petclinic-config